apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app: test
    includeSelectors: true # <-- false by default
    includeTemplates: true
resources:
- deployment.yaml

patches:
 - path: affinity.yaml
 - path: nodeselector.yaml
 - path: probe.yaml

