apiVersion: apps/v1
kind: Deployment
metadata:
  name: default
spec:
  template:
    spec:
      containers:
        - name: defaultcontainer
          startupProbe:
            httpGet:
              path: /this
              port: 3000
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /this
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 1
            failureThreshold: 3
            successThreshold: 2
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /this
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 2
            timeoutSeconds: 3      
