apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  template:
    spec:
      containers:
        - name: helloworld
          image: elsvent/helloworld:1.0.0
          env:
          - name: MESSAGE
            value: "hello devopsdays japan 2025"
          ports:
          - name: web
            containerPort: 3000