apiVersion: apps/v1
kind: Deployment
metadata:
  name: default
spec:
  template:
    spec:
      containers:
        - name: defaultcontainer
          resources:
            requests:
              cpu: 100m
              memory: '512Mi'
            limits:
              cpu: 500m
              memory: '1024Mi'         